name: turbostart-npm
description: A simple action to setup node, install npm dependencies, and cache for later use.
branding:
  icon: package
  color: red
runs:
  using: composite
  env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ vars.TURBO_TEAM }}

  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.5.3

    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0

    - name: Install Dependencies
      shell: bash
      run: npm ci --ignore-scripts
