name: turbostart-npm
description: A simple action to setup node, install npm dependencies, and cache for later use.
branding:
  icon: package
  color: red
runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3.5.3

    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0

    - name: Clean Install Dependencies
      shell: bash
      run: npm ci --ignore-scripts

    - name: Cache Dependencies
      uses: actions/cache@v3.2.4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
